# Name of workflow
name: Node CI

# Trigger the workflow on push or pull request
on:
  - push

  jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: runlinter
        run: |
          make lint
